const baseProjects = [
  {
    numProject: 5,
    name: "Site Internet Portfolio",
    context: "Personnel",
    type: "site",
    stack: "React.js, Javascript, CSS",
    length: "1 semaine",
    description:"Site ayant pour objectif de présenter mon parcours et mes projets de manière épurée",
    image:"public/images/illuProjetSite.png",
    image2:"public/images/illuProjetSite.png",
    link: "vous y êtes! :)",
    github: "https://github.com/EmmanuelleBonoli/site-cv-perso",
  },
  {
    numProject: 4,
    name: "Clash Heroes",
    context: "Formation",
    type: "jeu",
    stack: "API externe, React.js, Javascript, CSS, Figma, Trello",
    length: "en cours",
    description:"jeu de combat entre super héros, réalisé selon la méthode agile (itération de sprints d'1semaine), sur la base de données API externe. Au programme : router, gestion des animations, réflexion UI/UX, et plein d'autres défis !!",
    image:"public/images/ClashHeroes.png",
    image2:"/public/images/ClashHeroes2.png",
    link: "à venir",
    github: "à venir",
  },
  {
    numProject: 3,
    name: "Game 8Ball",
    context: "Formation",
    type: "jeu",
    stack: "React.js, Javascript, CSS",
    length: "quelques heures (non responsif)",
    description:"Jeu reprenant le concept de la MagicBall proposant des réponses aléatoires aux questions de l'utilisateur",
    image:"/public/images/Game8Ball.png",
    image2:"/public/images/ball8.png",
    link: "https://game-8-ball-6dhy5x9vu-emmanuelle-bonolis-projects.vercel.app",
    github: "https://github.com/EmmanuelleBonoli/Game-8Ball",
  },
  {
    numProject: 2,
    name: "Yahtzee",
    context: "Personnelle",
    type: "jeu",
    stack: "React.js, Javascript, CSS",
    length: "en cours",
    description:"Jeu de Yam's classique",
    image:"/public/images/Yahtzee.png",
    image2:"",
    link: "à venir",
    github: "à venir",
  },
  {
    numProject: 1,
    name: "GymStudio",
    context: "Formation",
    type: "site",
    stack: "Javascript vanilla, CSS, HTML",
    length: "2 semaines",
    description:"Site vitrine pour une entreprise de coachs sportifs",
    image:"/public/images/GymStudio.png",
    image2:"/public/images/logoGymStudio.png",
    link: "https://hlnvrnt.github.io/GymStudio",
    github: "https://github.com/EmmanuelleBonoli/GymStudio",
  },
];

export default baseProjects
