const baseProjects = [
  {
    numProject: 5,
    name: "Yahtzee",
    context: "Personnelle",
    type: "jeu",
    stack: "React.js, Javascript, CSS",
    length: "1mois et demi",
    description: "Jeu de Yam's classique",
    image: "/images/yahtzee.png",
    image2: "/images/yahtzee2.png",
    link: "https://major-game-yahtzee.vercel.app",
    github: "https://github.com/EmmanuelleBonoli/Yathzee",
  },
  {
    numProject: 4,
    name: "Clash Heroes",
    context: "Formation",
    type: "jeu",
    stack: "API externe, React.js, Javascript, CSS, Figma, Trello",
    length: "4 semaines",
    description:
      "jeu de combat entre super héros, réalisé selon la méthode agile.",
    image: "/images/ClashHeroes.png",
    image2: "/images/ClashHeroes2.png",
    link: "https://clash-heroes.vercel.app",
    github: "https://github.com/Tony97421/wild-clash",
  },
  {
    numProject: 3,
    name: "Site Internet Portfolio",
    context: "Personnelle",
    type: "site",
    stack: "React.js, Javascript, CSS",
    length: "1 semaine",
    description:
      "Site ayant pour objectif de présenter mon parcours et mes projets de manière épurée",
    image: "/images/illuProjetSite.png",
    image2: "/images/illuProjetSite.png",
    link: "vous y êtes! :)",
    github: "https://github.com/EmmanuelleBonoli/site-cv-perso",
  },
  {
    numProject: 2,
    name: "Game 8Ball",
    context: "Formation",
    type: "jeu",
    stack: "React.js, Javascript, CSS",
    length: "quelques heures (non responsif)",
    description:
      "Jeu reprenant le concept de la MagicBall proposant des réponses aléatoires aux questions de l'utilisateur",
    image: "/images/Game8Ball.png",
    image2: "/images/ball8.png",
    link: "https://game-8-ball-6dhy5x9vu-emmanuelle-bonolis-projects.vercel.app",
    github: "https://github.com/EmmanuelleBonoli/Game-8Ball",
  },
  {
    numProject: 1,
    name: "GymStudio",
    context: "Formation",
    type: "site",
    stack: "Javascript vanilla, CSS, HTML",
    length: "2 semaines",
    description: "Site vitrine pour une entreprise de coachs sportifs",
    image: "/images/GymStudio.png",
    image2: "/images/gymstudio2.png",
    link: "https://hlnvrnt.github.io/GymStudio",
    github: "https://github.com/EmmanuelleBonoli/GymStudio",
  },
];

export default baseProjects;
